### ISSUE TITLE
Runner plugin example does not work when using traceur transpiler

### ISSUE THREAD

**Issue by hitmanmcc** [getify/asynquence#80]
Hello guys,

This is more of a traceur problem as I see it, then it is yours but I figured I would just let you guys know that I tried one of your samples for the runner plugin (the one using a generator) and it does not work when using traceur to transpile. However, if I use babel, it runs fine.
The error output to the console is: "Sent value to newborn generator."
As I understand it, this would be related to the first value being sent to the next() call not being undefined.

**Comment by getify** [comment]
Correct. It would appear that traceur is still holding to an old rule that was clarified later in the ES6 spec process, which relaxed the validations and allowed values to be sent to `next(..)` even on its first call. Traceur needs to be updated to be spec compliant.

Unfortunately there's no way for asynquence to change here, that I can see, because there's no way to distinguish reliably that this error came from that problem vs catching another error that just legitimately happened on the inside of a generator. Parsing the error message text is pretty hacky and could very well be unreliable.

**Comment by hitmanmcc** [comment]
Yes indeed, I looked it up and I found a thread explaining just that. This posting was just more of a heads-up for people that may run into the same issue. :)
I wasn't expecting that you guys would be able to circumvent this in a predictable fashion as this really is a problem with the transpiler. Anyway, thanks for the validation.
